version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-auth
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  auth-service:
    build: .
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb-auth:27017/productcatalog
    depends_on:
      - mongodb

volumes:
  mongo-data:
