version: '3.8'

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/authdb
    networks:
      - backend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - backend

networks:
  backend:
    driver: bridge
