version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-product-catalog
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  product-catalog-service:
    build: .
    container_name: product-catalog-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb-product-catalog:27017/productcatalog
    depends_on:
      - mongodb

volumes:
  mongo-data: