version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-cart
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  cart-service:
    build: .
    container_name: cart-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb-cart:27017/cartdb
    depends_on:
      - mongodb

volumes:
  mongo-data: