version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-user
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb-user:27017/userdb
    depends_on:
      - mongodb

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb-auth:27017/productcatalog
    depends_on:
      - mongodb

volumes:
  mongo-data:
